<a href="https://colab.research.google.com/github/desakim/ESAA_YB2/blob/main/desakim_YB2_3_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [75]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [76]:
print(np.__version__)
print(np.show_config())

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [77]:
array1 = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [78]:
print(array1.size * array1.itemsize)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [79]:
array2 = np.zeros(10)
array2[4] = 1
print(array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [80]:
array3 = np.arange(start=10, stop=50)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [81]:
print(array3[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [82]:
array4 = np.arange(9).reshape(3,3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [83]:
array5 = np.array([1,2,0,0,4,0])
np.nonzero(array5)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [84]:
print(np.identity(3))
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [85]:
print(np.random.random((3,3,3)))

[[[0.76007544 0.68540206 0.09000585]
  [0.01466066 0.51106866 0.10647843]
  [0.4367217  0.49967186 0.61453331]]

 [[0.82537808 0.60221638 0.88852433]
  [0.23828057 0.29680361 0.56270853]
  [0.52385655 0.69269633 0.39253155]]

 [[0.48974067 0.35839857 0.55206732]
  [0.20570942 0.28496677 0.73308653]
  [0.85613593 0.56917398 0.44614132]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [86]:
array6 = np.random.random((10,10))
print(np.min(array6), np.max(array6))

0.005048906031883238 0.9978569833429521


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [87]:
vector1 = np.random.random(30)
print(np.mean(vector1))

0.5491811981473403


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

---



In [88]:
array7 = np.ones((5,5))
array7[1:-1,1:-1] = 0
print(array7)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

Ans) nan, False, False, nan, True, False

In [89]:
0 * np.nan

nan

In [90]:
np.nan == np.nan

False

In [91]:
np.inf > np.nan

False

In [92]:
np.nan - np.nan

nan

In [93]:
np.nan in set([np.nan])

True

In [94]:
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [95]:
matrix1 = np.diag(1+np.arange(4), k = -1)
print(matrix1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [96]:
matrix2 = np.ones((8,8))
for i in range(8):
  for j in range(8):
    if (i+j)%2 == 0:
      matrix2[i,j] = 0
print(matrix2)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [97]:
array8 = np.arange(6*7*8).reshape(6,7,8)
print(array8)
print(np.unravel_index(99, (6,7,8)))

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [98]:
matrix3 = np.random.random((5,5))
print((matrix3 - np.mean(matrix3))/np.std(matrix3))

[[ 1.70300124 -0.13478683 -1.44145555 -1.07313735 -0.64189693]
 [ 1.22122577  0.28319522  0.23171869  0.15779519 -1.2132013 ]
 [ 0.87192629  1.63147258  0.5152121  -1.21481033  0.82817967]
 [ 0.81110998  0.15240816 -1.07435024 -1.29925806  0.04889784]
 [-0.2659705  -1.56758982  1.50785006 -0.77403847  0.7365026 ]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [99]:
np.dtype([('r', np.ubyte),('g', np.ubyte),('b', np.ubyte),('a',np.ubyte)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [100]:
A = np.arange(5*3).reshape(5,3)
B = np.arange(3*2).reshape(3,2)
np.dot(A,B)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [101]:
array8 = np.arange(11)
array8[(3 <= array8) & (array8 <= 8)] *= -1
print(array8)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9, 10

In [102]:
print(sum(range(5),-1)) # 합에 -1 한 것
from numpy import *
print(sum(range(5),-1)) # 1차원에서 더한 것

10
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Ans) 6번째.

In [103]:
Z = np.array([1,2,3,4])

In [104]:
print(Z**Z)

[  1   4  27 256]


In [105]:
print(2 << Z >> 2)

[1 2 4 8]


In [106]:
print(Z <- Z)

[False False False False]


In [107]:
print(1j*Z)

[0.+1.j 0.+2.j 0.+3.j 0.+4.j]


In [108]:
print(Z/1/1)

[1. 2. 3. 4.]


In [109]:
print(Z<Z>Z)

ValueError: ignored

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

Ans) nan, 0, array([-9.22337204e+18])

In [111]:
np.array(0) / np.array(0)

<ipython-input-111-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [112]:
np.array(0) // np.array(0)

<ipython-input-112-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [113]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [114]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [115]:
import numpy as np

In [116]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-116-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

Ans) False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [117]:
Z = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [118]:
A = np.ones(3) * 1
B = np.ones(3) * 2

np.add(A,B,out = B)
np.divide(A,2,out = A)
np.negative(A,out = A)
np.multiply(A,B,out = A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [119]:
Z = np.random.uniform(0,10,10)
 
print(Z - Z%1) 
print(Z//1) 

[6. 3. 6. 9. 0. 8. 0. 0. 2. 0.]
[6. 3. 6. 9. 0. 8. 0. 0. 2. 0.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [120]:
Z = np.zeros((5,5))
Z += np.arange(5) 
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [121]:
array = np.random.random(10)
print(array)

array.sort()
array     

[0.88635003 0.00578132 0.62006216 0.12567987 0.72342501 0.47907876
 0.13330032 0.84952294 0.34061139 0.35208957]


array([0.00578132, 0.12567987, 0.13330032, 0.34061139, 0.35208957,
       0.47907876, 0.62006216, 0.72342501, 0.84952294, 0.88635003])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [122]:
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [123]:
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]

R = np.sqrt(X**2 + Y ** 2) # (0,0)에서 해당 점까지의 거리
P = np.arctan2(Y,X) # 극좌표계

print(R)
print(P)

[0.92284898 0.84268415 1.21020176 0.67549609 0.87817487 0.99022872
 0.90317213 0.1520763  0.93315957 0.3403993 ]
[0.06729356 0.56783548 0.73537275 0.00688551 1.01419125 1.52891356
 0.08860671 1.24670532 1.47606664 0.57510281]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [124]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.61252298 0.88965013 0.36015925 0.10967553 0.39632845 0.88472936
 0.7767155  0.074062   0.77624843 0.10125295]
[0.61252298 0.         0.36015925 0.10967553 0.39632845 0.88472936
 0.7767155  0.074062   0.77624843 0.10125295]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [125]:
Z = np.arange(100)
v = np.random.uniform(0,100)
r = np.abs(Z-v)
Z[r.argmin()]

83

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [126]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
  print(index, value)

for index in np.ndindex(Z.shape):
  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [127]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),4)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [128]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 5 8]
 [8 3 8]
 [7 9 0]]
[[8 3 8]
 [3 5 8]
 [7 9 0]]
